[package]
name = "timbre"
version = "0.1.0"
authors = ["Thoren Paulson <thoren.paulson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.34.0", features = ["bundled"] }
slotmap = "0.4.0"
